name: Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"
      - name: Compile
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: |
          echo -n $GOOGLE_CLIENT_ID >client_id
          echo -n $GOOGLE_CLIENT_SECRET >client_secret
          GOOS=windows go build
          GOOS=linux go build
          rm -f client_{id,secret}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            gmailbkp.exe 
            gmailbkp
